### ISSUE TITLE
install MicroMagnum

### ISSUE THREAD

**Issue by bp-mbi** [lrlunin/mbi-div-b-notebook#8]
Yet another micromagnetic simulation tool. This is heavily used by Kai Litzius (Uni Augsburg). We collaborate with Kai a lot and would be great if we could run his code on our machine as well.

https://github.com/MicroMagnum/MicroMagnum

**Comment by lrlunin** [comment]
The repository was updated 11 years ago for the last time. Could you ask Kai whether it is the last version or a newer version was moved into other repository.
